USE ventas;

SELECT nombre_emp,  puesto, nombre_depto
FROM emp e
INNER JOIN depto d 
ON e.clave_depto = d.clave_depto;

SELECT DE.NOMBRE_DEPTO, P.DESCRIPCION, ROUND(SUM(D.CANTIDAD),1) TOTAL
FROM PRODUCTOS P
INNER JOIN DETALLES_PEDIDO D
ON P.CLAVE_PRODUCTO = D.CLAVE_PRODUCTO
INNER JOIN PEDIDOS PE
ON D.CLAVE_PEDIDO = PE.CLAVE_PEDIDO
INNER JOIN CLIENTES C
ON PE.CLAVE_CLIENTE = C.CLAVE_CLIENTE
INNER JOIN EMP E
ON C.CLAVE_EMP_VENDEDOR = E.CLAVE_EMP
INNER JOIN DEPTO DE
ON E.CLAVE_DEPTO = DE.CLAVE_DEPTO
WHERE DESCRIPCION LIKE "%TENNI%"
GROUP BY P.CLAVE_PRODUCTO
HAVING TOTAL > 100
ORDER BY TOTAL DESC;